version: "3.9"
services:
  fphp-workshop:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      SERVER_NAME: localhost
      PROJECT_ROOT: /app
      DOCUMENT_ROOT: /app/public
      APP_ENV: dev
      APP_DEBUG: true
      FIX_FILE_PERMISSIONS_ON_START: true
      PHP_IDE_CONFIG: "serverName=frankenphp"
      XDEBUG_ENABLE: 1
      XDEBUG_START_WITH_REQUEST: yes
      XDEBUG_MODE: debug,develop
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./src:/app:rw
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:rw
      - caddy_data:/data/caddy
      - caddy_config:/config/caddy
volumes:
  caddy_data:
      driver: local
  caddy_config:
      driver: local