version: "3.9"
services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      PROJECT_ROOT: ${PROJECT_ROOT:-/app}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT:-/app/public}
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-true}
      FIX_FILE_PERMISSIONS_ON_START: ${FIX_FILE_PERMISSIONS_ON_START:-true}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-"serverName=frankenphp"}
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-1}
      XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST:-yes}
      XDEBUG_MODE: ${XDEBUG_MODE:-debug,develop}
      GIT_USER_NAME: ${GIT_USER_NAME:-"frankenphp"}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL:-"frankenphp@gmail.com"}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT_HTTP:-80}:80" # HTTP
      - "${PORT_HTTPS:-443}:443" # HTTPS
      - "${PORT_HTTPS3:-443}:443/udp" # HTTP/3
    volumes:
      - ./src:/app:rw
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:rw
      - caddy_data:/data/caddy
      - caddy_config:/config/caddy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-homestead}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    ports:
      - "${PORT_MYSQL:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  mysql_data:
    driver: local